// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package fetch

import (
	"database/sql"
	"time"
)

type Branch struct {
	ID        int64
	Name      string
	Path      string
	PgID      sql.NullInt64
	ParentID  int64
	DatasetID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Pg struct {
	ID        int64
	Name      string
	Path      string
	Version   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Repo struct {
	ID        int64
	Name      string
	PgID      sql.NullInt64
	DatasetID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ZfsDataset struct {
	ID     int64
	Name   string
	PoolID sql.NullInt64
}

type ZfsPool struct {
	ID     int64
	Name   string
	LoopNo int64
}
