// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dao

import (
	"database/sql"
	"time"
)

type Branch struct {
	ID        int64
	Name      string
	RepoID    int64
	ParentID  sql.NullInt64
	DatasetID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Pg struct {
	ID             int64
	PgPath         string
	Version        int64
	StopPg         bool
	PgUser         string
	ConnectionType string
	Host           sql.NullString
	Port           sql.NullInt64
	Username       sql.NullString
	Password       sql.NullString
	Status         string
	Output         sql.NullString
	RepoID         int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Repo struct {
	ID        int64
	Name      string
	PoolID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Setting struct {
	ID        int64
	Key       string
	Value     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ZfsDataset struct {
	ID        int64
	Name      string
	PoolID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ZfsPool struct {
	ID        int64
	Path      string
	SizeInMb  int64
	Name      string
	MountPath string
	PoolType  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
