// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dao

import (
	"database/sql"
	"time"
)

type Branch struct {
	ID        int64
	Name      string
	Path      string
	ParentID  int64
	DatasetID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Pg struct {
	ID        int64
	Name      string
	Path      string
	Version   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Repo struct {
	ID        int64
	Name      string
	RepoType  string
	Size      int64
	SizeUnit  string
	PoolID    int64
	PgID      sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ZfsDataset struct {
	ID        int64
	Name      string
	PoolID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ZfsPool struct {
	ID        int64
	Path      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
