CREATE TABLE IF NOT EXISTS branches
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       VARCHAR(255) NOT NULL,
    path       VARCHAR(255) NOT NULL,
    pg_id      INTEGER REFERENCES pg (id) ON DELETE CASCADE,
    parent_id  INTEGER      NOT NULL REFERENCES branches (id) ON DELETE CASCADE,
    dataset_id INTEGER      NOT NULL REFERENCES zfs_dataset (id) ON DELETE CASCADE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
