CREATE TABLE credential
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id    INTEGER      NOT NULL REFERENCES repo (id) ON DELETE CASCADE,
    PASSWORD   VARCHAR(255) NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
