CREATE TABLE settings
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    key        VARCHAR(255) NOT NULL UNIQUE,
    value      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
