CREATE TABLE IF NOT EXISTS zfs_pool
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    path       VARCHAR(2048) NOT NULL,
    name       VARCHAR(255)  NOT NULL,
    created_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS zfs_dataset
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       VARCHAR(255) NOT NULL,
    pool_id    INTEGER      NOT NULL REFERENCES zfs_pool (id) ON DELETE CASCADE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
